matrix:
  SCALA_VERSION:
    - 2.10.6
    - 2.11.8
  TEST_SUITE:
    - test it:test

build:
  image: chipsenkbeil/scala-debugger:latest
  pull: true
  environment:
    - SBT_TASK_LIMIT=4
    - SCALATEST_PARALLEL_TESTS=2
    - SCALATEST_SLEEP_SCALE_FACTOR=2.0
    - CACHE_DIR="/drone"
    - SCALATEST_SPAN_SCALE_FACTOR=10
  commands:
    - host `curl -s http://httpbin.org/ip | jq -r '.origin'` || true
    - javac -version
    - /usr/bin/sbt ++$SCALA_VERSION $TEST_SUITE

