package org.scaladebugger.api.profiles.scala210.info

/**
 * Represents various rules and patterns used across Scala 2.10.
 */
object Rules {
  // Construct regex to handle different naming conventions
  // where the first group matches the desired name
  private lazy val ParsePatterns = Seq(
    // Grab tail end of org$scaladebugger$class$$fieldName
    // as well as org.scaladebugger.class.fieldName
    """(?:\w+[\$|\.]+)*([^\$\d]\w*)""",

    // Grab the start of variables like x$1 and y$1
    """(\w+)\$(?:\d\w*)"""
  ).map("(?:^" + _ + "$)").map(_.r)

  /**
   * Extracts the Scala name from the raw Java name generated by Scala 2.10.
   *
   * @param rawName The raw name generated by Scala 2.10
   * @return The Scala 2.10 name
   */
  def extractName(rawName: String): String = {
    ParsePatterns
      .flatMap(_.findFirstMatchIn(rawName))
      .flatMap(m => Option(m.group(1)))
      .headOption.getOrElse(rawName)
  }
}
